import Head from 'next/head'
import { useState } from 'react'
import { CONTRACT_ABI, CONTRACT_ADDRESS } from '../utils/contract'
import {ethers} from 'ethers'



export default function Home() {

  const [address, setAddress] = useState(null)
  const [contract, setContract] = useState(null)
  const [loading, setLoading] = useState(false)

  const connectWallet = async () => {
    if (window) {
      const { ethereum } = window
      if (ethereum) {
        try {
          const accounts = await ethereum.request({
            method: "eth_requestAccounts"
          })
          console.log(accounts)
          setAddress(accounts[0])
          let provider = new ethers.providers.Web3Provider(ethereum)
          let signer = provider.getSigner()
          let c = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer)
          setContract(c)
        } catch (err) {
          console.log(err)
        }
      }
    }
  }
  console.log("ADDRESS", address)
  console.log("CONTRACT", contract)
  const mintNFT = async () => {
    try {
      setLoading(true)
      const mint = await contract.safeMint()
      await mint.wait()
      console.log("Minted", mint)
      setLoading(false)
    } catch (err) {
      console.log(err)
      setLoading(false)
    }
  }
  return (
    <div>
      <Head>
        <title>Connecting Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center min-h-screen">
        <h1 className="text-4xl font-extrabold">Interact with contract</h1>
        {
          address ? (
            <button onClick={mintNFT} className='py-2 px-4 rounded-xl bg-white text-black transform hover:scale-105'>Mint NFT</button>
          ) : (
            <button onClick={connectWallet} className='py-2 px-4 rounded-xl bg-white text-black transform hover:scale-105'>Connect Wallet</button>
          )
        }
        
      </main>
    </div>
  )
}
